/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#pragma mark -

/*
 * File: iPhone Simulator
 * UUID: 67F4F6E1-E0F5-3EEE-AEC7-8C2852FE95F1
 * Arch: Intel 80x86 (i386)
 *
 *       Objective-C Garbage Collection: Unsupported
 */

@protocol SimulatorViewProtocol
- (void)setMonitorViewController:(id)arg1;
@end

@interface MonitorController : NSObject
//{
//    PreferencesController *_preferencesController;
//    NSMenu *devicesMenu;
//    NSMenu *versionsMenu;
//    MonitorWindow *_monitorWindow;
//    NSMenuItem *_ringerMenuItem;
//    NSScreen *_lastScreen;
//    SimulatorFrameView *_simulatorBox;
//    NSView<SimulatorViewProtocol> *_simulatorView;
//    SimulatorHomeView *_homeView;
//    SimulatorGlassView *_glassView;
//    SimulatorGlassWindow *_glassWindow;
//    int _tvOutMode;
//    NSWindow *_tvOutWindow;
//    MonitorViewController *_tvOutMonitorViewController;
//    NSView<SimulatorViewProtocol> *_tvOutSimulatorView;
//    float _rotation;
//    struct CGAffineTransform _transform;
//    BOOL _inRotation;
//    MonitorViewController *_monitorViewController;
//    NSConditionLock *eventForwardingLock;
//    ProcessControl *_simulatedProcess;
//    NSAppleScript *_showProgrammingGuideScript;
//    struct _NSPoint _startingSimulatorViewInset;
//    BOOL _useLegacyEventStructSize;
//    BOOL _simulatingHardwareKeyboard;
//    BOOL _sdkSupportsHostedLayerEvents;
//    BOOL _demoMode;
//    BOOL _enableMirrorScreens;
//    BOOL _mirrorOnly;
//    BOOL _mirrorScreenConnected;
//    BOOL _mirrorScreenEvents;
//    NSWindow *_mirrorWindow;
//    NSView<SimulatorViewProtocol> *_mirrorView;
//    struct CGAffineTransform _mirrorTransform;
//    BOOL _mirrorNeedsRotation;
//    struct _NSSize _reccomendedWindowSize;
//    float _monitorWindowScale;
//    int _monitorWindowType;
//    NSScrollView *_monitorScrollView;
//    NSBundle *_deviceBundle;
//    id _deviceBundleObject;
//}

+ (id)sharedInstance;
- (void)copy:(id)arg1;
- (void)paste:(id)arg1;
- (void)copyScreen:(id)arg1;
@end